// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa2y3_SSxyHKSTi_dC4LVPJyZiCdg2U6g',
    appId: '1:312924286511:web:bdfc37967c2d627fa960da',
    messagingSenderId: '312924286511',
    projectId: 'study-app-936e2',
    authDomain: 'study-app-936e2.firebaseapp.com',
    storageBucket: 'study-app-936e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1o6b2B6FqKGtaakc-xmL1lQE891LkJKk',
    appId: '1:312924286511:android:83541ab73e4da050a960da',
    messagingSenderId: '312924286511',
    projectId: 'study-app-936e2',
    storageBucket: 'study-app-936e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBGEJ7qh_IMBpgEoaZOl4d_xK9Fccvz8o',
    appId: '1:312924286511:ios:f46ce620cc6f54a8a960da',
    messagingSenderId: '312924286511',
    projectId: 'study-app-936e2',
    storageBucket: 'study-app-936e2.appspot.com',
    iosClientId: '312924286511-6vt5tu6sokjp1e819ga7iff6jcjhbcuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
